spring:
  application:
    name: Order
server:
  port: 8101
restApi:
  swagger:
    title: springdemo-订单webapi
    version: 1
    description: 订单webapi!！！
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/