spring:
  cloud:
    stream:
      bindings:
        output:
          destination: p-input
          binder: rabbit1
          producer:
            partitionCount: 2
            partitionKeyExpression: payload
      binders:
        rabbit1:
          type: rabbit
          defaultCandidate: false
          environment:
            spring:
              rabbitmq:
                host: 172.18.115.15
                username: guest
                password: guest
server:
  port: 8627