spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://172.18.115.132:3306/lr_logtest
    username: base
    password: base1234
  cloud:
    stream:
      bindings:
        output:
          destination: p-input
          content-type: application/json
          binder: kafka1
          producer:
            partitionCount: 2
            partitionKeyExpression: payload
      binders:
        rabbit1:
          type: rabbit
          defaultCandidate: false
          environment:
            spring:
              rabbitmq:
                host: 172.18.115.15
                username: guest
                password: guest
        kafka1:
          type: kafka
          defaultCandidate: false
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: 172.18.115.47,172.18.115.48,172.18.115.49
              zkNodes: 172.18.115.47,172.18.115.48,172.18.115.49
server:
  port: 8627