spring:
  cloud:
    stream:
      bindings:
        input:
          destination: output
          binder: rabbit1
          group: GroupB
#          consumer:
#            partitioned: true
#            instance-count: 2
#            instance-index: 0
        output:
          destination: input
          binder: rabbit1
#          producer:
#            partitionCount: 2
      binders:
        rabbit1:
          type: rabbit
          defaultCandidate: false
          environment:
            spring:
              rabbitmq:
                host: 172.18.115.15
                username: guest
                password: guest
server:
  port: 8627