eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka
  server:
    enable-self-preservation: true
server:
  port: 8082