spring:
  application:
    name: News
server:
  port: 8201
restApi:
  swagger:
    title: springdemo-新闻webapi
    version: 1
    description: 新闻webapi!！！
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
User:
  ribbon:
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: true
    ConnectTimeout: 250
    ReadTimeout: 500
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2000
management:
  endpoints:
    web:
      base-path: