spring:
  application:
    name: Turbine
server:
  port: 8060
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
turbine:
  combine-host-port: true
  clusterNameExpression: "'default'"
  app-config: Order,News
